name: workflow-dev

on:
  push:
    branches:
      - task/EPS-test-Runner
  pull_request:
    branches:
      - task/EPS-test-Runner

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: echo Hello  # Replace with your specific test command

      - name: Set environment variables
        run: |
          chmod +x ./.github/workflows/env.sh
          ./.github/workflows/env.sh  # Run the script to set environment variables
        shell: bash

      - name: Display Updated test.json
        run: cat ./test.json
