name: workflow-dev

on:
  push:
    branches:
      - task/EPS-test-Runner
  pull_request:
    branches:
      - task/EPS-test-Runner

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print Secret Value
        run: |
          echo "Secret value: ${{ secrets.AZURE_APIKEY }}"
        env:
          AZURE_APIKEY: ${{ secrets.AZURE_APIKEY }}
        shell: bash
      - name: Display Updated test.json
        run: cat ./test.json
