name: my-workflow  # Name of your workflow

on:  # Triggers the workflow
  push:  # On pushes to branches
    branches: [ task/EPS-test-Github-Runner ] 
  pull_request:  # On pull requests
    branches: [ task/EPS-test-Github-Runner ]
  # workflow_dispatch:
jobs:
  build:  # Name of the job

    runs-on: 
    - self-hosted  # The type of GitHub-hosted runner
    - label-1
    steps:  # Steps within the job
      - uses: actions/checkout@v3  # Checks out your repository
      - name: Run tests
        run:
          echo Hello  # Replace with your specific test command
